---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  vars:
    aws_region: "af-south-1"
    ssh_default_port: 22
    keypair_name: "afs1-hakkutu-dev-ansible-role-openscap"
    security_group_name: "afs1-hakkutu-dev-ansible-role-openscap"
    security_group_description: "Security group for ansible role - ansible_role_openscap"

  tasks:
    - name: Ensure a local SSH keypair is created
      register: ssh_keypair
      community.crypto.openssh_keypair:
        path: "{{ molecule_ephemeral_directory }}/{{ keypair_name }}"
        type: "ed25519"
        state: "present"

    - name: Ensure an AWS keypair is created
      when:
        - ssh_keypair.changed | default(false) | bool
        - lookup('file', molecule_ephemeral_directory + '/' + keypair_name + '.pub') is defined
      register: aws_keypair
      amazon.aws.ec2_key:
        name: "{{ keypair_name }}"
        key_material: "{{ lookup('file', molecule_ephemeral_directory + '/' + keypair_name + '.pub') }}"
        region: "{{ aws_region }}"

    - name: Ensure that a security group is created
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_description }}"
        rules:
          - proto: "tcp"
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"

    - name: Ensure that instances are created
      loop: "{{ molecule_yml.platforms }}"
      register: server
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        image_id: "{{ item.image_id }}"
        instance_type: "{{ item.instance_type }}"
        key_name: "{{ keypair_name }}"
        volumes:
          - device_name: "{{ item.ebs_device_name | default('/dev/sda1') }}"
            ebs:
              volume_size: "{{ item.ebs_volume_size | default(30) }}"
              delete_on_termination: true
        region: "{{ aws_region }}"
        metadata_options:
          http_endpoint: "enabled"
          http_tokens: "required"
          http_put_response_hop_limit: 2
        tags:
          Name: "{{ item.name }}"
          DefaultUser: "{{ item.ssh_username }}" # will fix later

    - name: Retrieve information for instances
      loop: "{{ server.results }}"
      register: ec2_instance_info
      until: >
        ec2_instance_info.instances[0].public_ip_address is defined and
        ec2_instance_info.instances[0].private_ip_address is defined
      retries: 20
      delay: 15
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          tag:Name: "afs1-hakkutu-dev-ansible-role-openscap-*"
          instance-state-name: ["pending", "running"]

    - name: Create instance config
      block:
        - name: Populate instance config dict
          loop: "{{ server.results }}"
          register: instance_config_dict
          ansible.builtin.set_fact:
            instance_conf_dict:
              instance: "{{ item.instances[0].tags.Name }}"
              address: "{{ item.instances[0].public_ip_address }}"
              user: "{{ item.instances[0].tags.DefaultUser }}"
              port: "{{ ssh_default_port }}"
              identity_file: "{{ molecule_ephemeral_directory }}/{{ keypair_name }}"

        - name: Convert instance config dict to a list
          ansible.builtin.set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Dump instance config
          ansible.builtin.copy:
            content: |
              # Molecule managed

              {{ instance_conf | to_json | from_json | to_yaml }}
            dest: "{{ molecule_instance_config }}"
            mode: "0600"
...