---
- name: Verify
  hosts: all
  gather_facts: true
  become: true

  vars:
    # Temporary directory for storing content
    tmp_directory: "/var/tmp/cis-benchmark"

    # Scap Security Guide content/package details
    scap_content_version: "0.1.76"
    scap_content_file: "scap-security-guide-{{ scap_content_version }}.zip"

    # Playbook run parameters
    scap_input_file_params:
      RedHat:
        content_base_directory: "/usr/share/xml/scap/ssg/content"
        profile: "cis"
        input_file:
          "8": "ssg-rhel8-ds.xml"
          "9": "ssg-rhel9-ds.xml"
      Amazon:
        content_base_directory: "{{ tmp_directory }}/{{ scap_content_file | splitext | first }}"
        profile: "cis"
        input_file:
          "2023": "ssg-al2023-ds.xml"
      Ubuntu:
        content_base_directory: "{{ tmp_directory }}/{{ scap_content_file | splitext | first }}"
        profile: "cis_level2_server"
        input_file:
          "22": "ssg-ubuntu2204-ds.xml"
          "24": "ssg-ubuntu2404-ds.xml"

    # Compliance percentage required
    compliance_percentage_required: 85

  tasks:
    - name: Ensure that the input file facts are set
      ansible.builtin.set_fact:
        xml_base_directory: "{{ scap_input_file_params[ansible_facts['distribution']]['content_base_directory'] }}"
        xml_name_part: "{{ scap_input_file_params[ansible_facts['distribution']]['input_file'][ansible_facts['distribution_major_version']] }}"

    # Hack for --> https://issues.redhat.com/browse/RHEL-88149
    - name: Hack for RHEL-88149 - RHEL 9
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "9"
      ansible.builtin.package:
        name: "libxslt-1.1.34-9.el9_5.1.x86_64"
        state: present
        allow_downgrade: true

    - name: Ensure scap report is generated
      ignore_errors: true # Lint failure - ignore-errors; wil fix later
      changed_when: false # Lint failure - no-changed-when
      ansible.builtin.command:
        chdir: "{{ tmp_directory }}"
        cmd: >
          oscap xccdf eval
           --profile {{ scap_input_file_params[ansible_facts['distribution']]['profile'] }}
           --report {{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}-report.html
           {{ xml_base_directory }}/{{ xml_name_part }}

    - name: Ensure that report file name is set
      ansible.builtin.set_fact:
        report_file_name: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}-report.html"

    - name: Retrieve the compliance percentage from managed nodes
      register: compliance_percentage
      changed_when: false
      ansible.builtin.shell:
        chdir: "{{ tmp_directory }}"
        executable: "/bin/bash"
        cmd: |
          set -o pipefail
          grep -E -o ".{0,6}%<" {{ report_file_name }} | tr -d "<",">","%",'"' | tr -d " "

    - name: Verify if compliance percentage is above {{ compliance_percentage_required }}%
      ansible.builtin.assert:
        that:
          - "compliance_percentage['stdout'] is version(compliance_percentage_required, '>=')"
        fail_msg: |
          The compliance percentage is below {{ compliance_percentage_required }}%.
          Current compliance percentage is {{ compliance_percentage['stdout'] }}%.
          Required compliance percentage is {{ compliance_percentage_required }}%.
        success_msg: |
          The compliance percentage has passed.
          Current compliance percentage is {{ compliance_percentage['stdout'] }}%.
          Required compliance percentage is {{ compliance_percentage_required }}%.
...
